language: python
python: 2.7
sudo: false

env:
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=pyflakes

matrix:
  fast_finish: true

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
